### ISSUE TITLE
Single end not supported in dev pipeline

### ISSUE THREAD

**Issue by fkollingiv** [Dartmouth-Data-Analytics-Core/DAC-RNAseq-pipeline#10]
The dev pipeline does not work for single end data. The issue appears due to the fact that the alignment rule (line 149) calls for R1 and R2 reads as input, which is only applicable for paired end data. Solution may be to specify inputs after the if statement for single vs paired, or nest the if statement for "aligner-name" within the if statement for single vs paired.

**Comment by owenwilkins** [comment]
OK thanks for pointing this out. Which branch are you using exactly, as there are currently a few with 'dev' in the title. In branch 'development' line 149 seems to be one of the final lines of the trimming rule for paired end? 

regarding the error, what is reported by snakemake when it exits? so that I didn't have to have separate alignment rules for single vs paired end, I generate a dummy R2 file in the single end trimming rule, which then meets the requirement for an R2 input file for the alignment rule for either paired or single end data. so I wouldn't have expected the lack of an R2 file into the alignment rule for single end data to be the issue, although perhaps its not being generated or there is an issue with it.

**Comment by tjs000** [comment]
I added conditions to the post-trimming inputs related to single vs. paired reads.  Let me know if that works for you!

**Comment by fkollingiv** [comment]
Just tested the updated pipeline on some single end data and it works great. Looks like we can close this issue.
