### ISSUE TITLE
STAR genome version not compatible with STAR version in conda

### ISSUE THREAD

**Issue by fkollingiv** [Dartmouth-Data-Analytics-Core/DAC-RNAseq-pipeline#22]
Receive the following error when running with STAR using the "built in" conda environment:

EXITING because of FATAL ERROR: Genome version: 2.7.1a is INCOMPATIBLE with running STAR version: 2.7.10a
SOLUTION: please re-generate genome from scratch with running version of STAR, or with version: 2.7.4a

the index I'm using is: aligner_index: '/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/mouse/STAR/GRCm38_index'

Let me know if you want me to update this or if DAC will do this.

**Comment by tjs000** [comment]
I've made a STAR 2.7.10a genome specifically for mouse, here:
`/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/mouse/STAR/2.7.10a/GRCm38_index`
You can use this as the aligner_index key in the config.yaml file.  

You probably already have the corresponding keys for the gtf, ref_flat, and interval_list.  This is how I would expect them to look altogether, for GRCm38:
```
aligner_index: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/mouse/STAR/2.7.10a/GRCm38_index"
annotation_gtf: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/mouse/ensembl-annotations/Mus_musculus.GRCm38.97.gtf"
picard_refflat: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/mouse/CollectRnaSeqMetrics/Mus_musculus.GRCm38.97.refFlat.txt"
picard_rrna_list: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/mouse/CollectRnaSeqMetrics/Mus_musculus.GRCm38.97.rRNA.interval_list
```

A goal of mine is to have pre-defined  star/hisat/rsem indexes, as well as GTF, ref_flat, and interval_list configurations for commonly-sequenced organisms, like human and mouse, available in a directory of config files, so that anyone using this pipeline doesn't have to figure out all these specifications.

**Comment by fkollingiv** [comment]
Thanks Tim, this is great. You beat me to it. I just kicked off the build_ref utility and that seems to be working well, but I'll use the one you built. Having these pre-defined would be great and would save a lot of copy/pasting of config files depending on the organism, love the idea!
